version: "3.8"

services:
  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    env_file:
      - ${POSTGRES_ENV_FILE}
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER}"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  backend_sportify:
    build:
      context: ../
      dockerfile: ./build/Dockerfile_sportify
      args:
        - CONFIG_FILE=${CONFIG_FILE}
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
