version: "3.8"

services:
  nginx:
    image: nginx:1.27-alpine
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/localhost.key:/etc/nginx/localhost.key
      - ./config/localhost.crt:/etc/nginx/localhost.crt
    ports:
      - "443:443"
    network_mode: "host"
  postgres:
    image: postgis/postgis:17-3.5
    restart: always
    env_file:
      - ${POSTGRES_ENV_FILE}
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER}"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  backend_sportify:
    build:
      dockerfile: ./build/Dockerfile_sportify
    restart: always
    ports:
      - "8080:8080"
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./sportify/photos:/var/sportify/photos
      - ${CONFIG_FILE}:/var/config/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  postgres:
  consul:
