bot:
  bot_token: "example_bot_token"
  port: ":8090"
  api_url: "http://localhost:8090/api/v1/message"

app:
  port: ":8080"
  api_prefix: "/api/v1/"
  path_photos: "./photos"
  folder_id: "example_folder_id"
  iam_token: "example_iam_toker"
  token_payment: "example_yookassa_token_payment"
  token_payout: "example_yookassa_token_payout"
  url_prefix_file: "http://127.0.0.1:8080/api/v1/img/"
  yookassa:
    shop_id: "example_shop_id"
    agent_id: "example_agent_id"
    token_payment: "example_yookassa_token_payment"
    token_payout: "example_yookassa_token_payout"
logger:
  production_mode: true
  logger_output: ["stdout"]
  logger_err_output: ["stderr"]
postgres:
  url: "postgres://postgres:postgres@postgres:5432/sportify?sslmode=disable"
