bot:
  bot_token: "example_bot_token"
  port: ":8090"

# sportify
app:
  api_url: "http://127.0.0.1:8080/api/v1/img/"
  port: ":8080"
  api_prefix: "/api/v1/"
  path_photos: "./photos"
  folder_id: "example_folder_id"
  iam_token: "example_iam_toker"
  url_prefix_file: "http://127.0.0.1:8080/api/v1/img/"
logger:
  production_mode: true
  logger_output: "stdout"
  logger_err_output: "stderr"
postgres:
  url_database: "postgres://postgres:postgres@postgres:5432/sportify?sslmode=disable"
