api_url: "http://localhost:8090/api/v1/message"
bot_token: "example_bot_token"

# sportify
production_mode: true
url_prefix_file: "http://127.0.0.1:8080/api/v1/img/"
port_public: ":8080"
port_tg: ":8090"
api_prefix: "/api/v1/"
path_photos: "photos"
folder_id: "example_folder_id"
iam_token: "example_iam_toker"
url_database: "postgres://postgres:postgres@postgres:5432/sportify?sslmode=disable"
logger_output: "stdout"
logger_err_output: "stderr"
