api_url: "http://localhost:8090/message"

# sportify
production_mode: true
port_public: ":8080"
port_tg: ":8090"
api_prefix: "/api/v1/"
path_photos: "./photos"
folder_id: "example_folder_id"
iam_token: "example_iam_toker"
url_database: "example_url_database"
logger_output: "stdout"
logger_err_output: "stderr"
